const header_kn_2_0_0_data = [
    {
        label: 'header_kn_2_0_0_dropdown-1',
        layout: '<li class="header_kn_2_0_0__head"><span class="header_kn_2_0_0__back">&#10094;</span>Dịch vụ</li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-tham-my-mat/">Thẩm mỹ mắt</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-tham-my-mui/">Thẩm mỹ mũi</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-tham-my-ham-mat/">Thẩm mỹ hàm và khuôn mặt</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-tao-hinh-voc-dang/">Thẩm mỹ ngực và vóc dáng</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-tre-hoa-da/">Trẻ hóa da công nghệ cao</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-da-lieu-va-dieu-tri-da-cong-nghe-cao/">Điều trị da công nghệ cao</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/dich-vu/chuyen-khoa-nha-khoa-tham-my/">Nha khoa thẩm mỹ</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="#">Kangnam Clinic (Phun xăm, triệt lông, tắm trắng)</a></li>'
    },
    {
        label: 'header_kn_2_0_0_dropdown-2',
        layout: '<li class="header_kn_2_0_0__head"><span class="header_kn_2_0_0__back">&#10094;</span>Bảng giá </li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-tham-my-mat">Thẩm mỹ mắt</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-tham-my-mui">Thẩm mỹ mũi</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-tham-my-ham-mat">Thẩm mỹ hàm và khuôn mặt</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-tham-my-voc-dang">Thẩm mỹ ngực và vóc dáng</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-tre-hoa-da-cong-nghe-cao">Trẻ hóa da công nghệ cao</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-dieu-tri-da-cong-nghe-cao">Điều trị da công nghệ cao</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/bang-gia/#bang-gia-nha-khoa-tham-my">Nha khoa thẩm mỹ</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="#">Kangnam Clinic (Phun xăm, triệt lông, tắm trắng)</a></li>'
    },
    {
        label: 'header_kn_2_0_0_dropdown-3',
        layout: '<li class="header_kn_2_0_0__head"><span class="header_kn_2_0_0__back">&#10094;</span>Ảnh trước - sau</li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-cat-mi">Thẩm mỹ mắt</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-nang-mui">Thẩm mỹ mũi</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-ham-mat">Thẩm mỹ hàm và khuôn mặt</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-nang-nguc">Thẩm mỹ ngực và vóc dáng</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-tre-hoa">Trẻ hóa da công nghệ cao</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-dieu-tri-da">Điều trị da công nghệ cao</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="https://benhvienthammykangnam.vn/hinh-anh-khach-hang/#dich-vu-nha-khoa">Nha khoa thẩm mỹ</a></li><li class="header_kn_2_0_0__dropdownItem"><a href="#">Kangnam Clinic (Phun xăm, triệt lông, tắm trắng)</a></li>'
    },
];