const doctors = [
  {
    name: "richard huy",
    image: `${doctor_kn_2_0_0_url}images/bacsi-small1.jpg?ver=2`,
    picture: `${doctor_kn_2_0_0_url}images/bacsi1.jpg?ver=2`,
    level: "tiến sĩ - Bác sĩ",
    position: "Giám đốc chuyên môn",
    note: "- Tiến sĩ y học - Đại học Y Hà Nội. <br> - 20 năm kinh nghiệm PTTM. <br> - Thành viên Hội phẫu thuật Tạo hình Thẩm mỹ Quốc tế (ISAPS).",
    link: 'https://benhvienthammykangnam.vn/doi-ngu-bac-si/richard-huy/',
  },
  {
    name: "henry nguyễn",
    image: `${doctor_kn_2_0_0_url}images/bacsi-small3.jpg?ver=3`,
    picture: `${doctor_kn_2_0_0_url}images/bacsi3.jpg?ver=3`,
    level: "bác sĩ",
    position: "chuyên gia thẩm mỹ gương mặt",
    note: "- Phó khoa Phẫu thuật thẩm mỹ gương mặt BVTM Kangnam. <br> - Trên 12 năm kinh nghiệm.",
    link: 'https://benhvienthammykangnam.vn/doi-ngu-bac-si/henry-nguyen/',
  },
  {
    name: "thủy lê",
    image: `${doctor_kn_2_0_0_url}images/bacsi-small4.jpg?ver=2`,
    picture: `${doctor_kn_2_0_0_url}images/bacsi4.jpg?ver=2`,
    level: "Bác sĩ CKI",
    position: "trưởng khoa da liễu",
    note: "- Bác sĩ CK1 đại học Y Hà Nội. <br> - Trưởng khoa da liễu BVTM Kangnam. <br> - Có 20 năm kinh nghiệm trong lĩnh vực điều trị da.",
    link: 'https://benhvienthammykangnam.vn/doi-ngu-bac-si/le-thi-thuy/',
  },
  {
    name: "Jolie huỳnh",
    image: `${doctor_kn_2_0_0_url}images/bacsi-small5.jpg?ver=2`,
    picture: `${doctor_kn_2_0_0_url}images/bacsi5.jpg?ver=2`,
    level: "Bác sĩ CKI",
    position: "giám đốc chuyên môn da liễu",
    note: "- Thạc sĩ - bác sĩ chuyên khoa da liễu. <br> - Tốt nghiệp trường Đại học Y dược HCM. <br> - Chuyên gia da liễu cao cấp 20 năm kinh nghiệm trong lĩnh vực điều trị da.",
    link: 'https://benhvienthammykangnam.vn/doi-ngu-bac-si/jolie-huynh/',
  },
  {
    name: "thomas nguyễn",
    image: `${doctor_kn_2_0_0_url}images/bacsi-small6.jpg?ver=2`,
    picture: `${doctor_kn_2_0_0_url}images/bacsi6.jpg?ver=2`,
    level: "Bác sĩ",
    position: "Chuyên gia tạo hình vóc dáng",
    note: "- Phó khoa Tạo hình vóc dáng BVTM Kangnam. <br> - Trên 10 năm kinh nghiệm.",
    link: 'https://benhvienthammykangnam.vn/doi-ngu-bac-si/thomas-nguyen/',
  },
  {
    name: "Edward Nguyễn",
    image: `${doctor_kn_2_0_0_url}images/bacsi-small8.jpg`,
    picture: `${doctor_kn_2_0_0_url}images/bacsi8.jpg`,
    level: "Bác sĩ",
    position: "Chuyên gia răng hàm mặt",
    note: "- Trưởng khoa Hàm mặt, Bệnh viện Thẩm mỹ Kangnam Sài Gòn. <br> - Cố vấn chuyên môn, bác sĩ phẫu thuật chương trình thực tế 'Hành trình Lột xác' <br/> - 10 năm kinh nghiệm trong lĩnh vực Hàm mặt.",
    link: 'https://benhvienthammykangnam.vn/doi-ngu-bac-si/edward-nguyen/',
  },
];
